---
title: "pcas and sems for hfd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyselect)
library(ggplot2)
library(broom)
library(dplyr)
library(corrplot)
library(kableExtra)
library(knitr)
library(Hmisc)
library(infer)
library(plotly) 
library(skimr)
library(stringr)
library(reshape2)
library(som)
library(manipulate)
library(lavaan)
library(semPlot)
library(FactoMineR)
library(factoextra)
library(readxl)
library(formattable)
library(DT)
library(xtable)
library(wesanderson)
library(psych)
```




```{r loading the data, echo=FALSE, warning=FALSE, message=FALSE}
normalized_ffostare_v1 <- read_excel("znormed_ffostare_v1.xlsx")
skim(normalized_ffostare_v1)
#znormed+ffostare and normalized are the same data set just renamed to reduce confusion; normalzied will be the Df moving forward with new data

#the znormed_ffostare_v1 is corrected output of ffo_corrected_spssout_full. then, for demographic information use selected_norms_composites_demgrafs_v1_use
normalized_ffostare_selectvars_v1 <- normalized_ffostare_v1 %>%
  select(-Observations, - ResultContainers, - Intervals, - Zno_sec_behav_ffosta)

View(normalized_ffostare_selectvars_v1)
```



```{r}
total_PCA_v1_5_20 <- prcomp(normalized_ffostare_selectvars_v1)

fviz_screeplot(total_PCA_v1_5_20, addlabels = TRUE)


View(eig_vals)


fviz_eig(total_PCA_v1_5_6)

datatable(formattable(as.data.frame(eig_vals)))

fviz_pca_ind(total_PCA_v1_5_6,
            col.ind = "cos2",
            repel = TRUE)

fviz_pca_ind(total_PCA_v1_5_6,
         geom.ind = "point",
         col.ind = as.factor("cos2"), 
         gradient = "Dark2",
         repel = F,
         addEllipses = TRUE
         )

total_PCA_var <- get_pca_var(total_PCA_v1_5_20)

eig_vals <- total_PCA_v1_5_20$sdev^2
barplot(eig_vals) + points(eig_vals) + lines(eig_vals)

datatable(formattable(as.data.frame(eig_vals)))

View(eig_vals)

```




```{r copy of original - do not use; use next chunk}
comp1_indi <- selected_norms_ffostare_v1 %>%
  select(Zstationary_middle_percent_butters, Zlocomotion_percent_butters, Zhanging_behaviors_butters, Ztactile_exploration_butters, Zmo_manip_apple_butters, Zstation_fr_ffostare,  Zstation_mid_ffosta, Zlocomote_ffosta, Zmovement_ffosta, Ztac_expl_ffosta,  Zstereo_ffosta, Zteethgrind_ffosta, Zlipsmack_ffosta, Ztouch_app_ffosta, Zmouth_app_ffosta, Zmanip_app_ffosta, Zeat_app_ffosta, Znonvigi_ffosta, Zdir_eye_contact_ffosta)






composite_active_vigilance <- normalized_ffostare_selectvars_v1 %>%
  select(Zlipsmack_ffosta, Zmovement_ffosta, Zdir_eye_contact_ffosta)

comp2_indi <- selected_norms_ffostare_v1 %>%
  select(ZStationary_back_butters, Zstereotypy_butters, Zvigilant_percent_butters, Zstation_back_ffostare, Zself_gro_ffosta, Zthreat_stranger_ffosta, Zfreeze_back_ffosta)

comp2.2_indi <- selected_norms_ffostare_v1 %>%
  select(Zstereotypy_butters, Zstation_back_ffostare, Zself_gro_ffosta, Zthreat_stranger_ffosta, Zfreeze_back_ffosta)

comp3_indi <- selected_norms_ffostare_v1 %>%
  select(Zstationary_front_percent_butters, Zmovement_percent_butters, Ztouch_butters_percent, Zcrouching_butters, Znonvigilant_percent_butters, Zcrouching_ffosta, Zvigi_ffosta, Zno_response_ffosta)

comp3.2_indi <- selected_norms_ffostare_v1 %>%
  select(ZStationary_back_butters, Zstationary_front_percent_butters, Zmovement_percent_butters, Zvigilant_percent_butters, Ztouch_butters_percent, Zcrouching_butters, Znonvigilant_percent_butters, Zcrouching_ffosta, Zvigi_ffosta, Zno_response_ffosta)

comp4_indi <- selected_norms_ffostare_v1 %>%
  select(Zself_groom_percent_butters, Zmouth_butters_percent, Zoral_exploration_butters)

```



```{r composite groups for PCA}
#self groom is interchangable with the next group 
composite_active_vigilance <- normalized_ffostare_selectvars_v1 %>%
  select(Zlipsmack_ffosta, Zmovement_ffosta, Zdir_eye_contact_ffosta)

##this is the significant variable
composite_active_anxiety <- normalized_ffostare_selectvars_v1 %>%
  select(Zstereotypy_butters, Zstation_back_ffostare, Zself_gro_ffosta, Zthreat_stranger_ffosta, Zfreeze_back_ffosta)

composite_inquisitive_vigilance <- normalized_ffostare_selectvars_v1 %>%
  select(ZStationary_back_butters, Zstationary_front_percent_butters, Zmovement_percent_butters, Zvigilant_percent_butters, Ztouch_butters_percent, Zcrouching_butters, Znonvigilant_percent_butters, Zcrouching_ffosta, Zvigi_ffosta, Zno_response_ffosta)

composite_novel_object_interest <- normalized_ffostare_selectvars_v1 %>%
  select(Zself_groom_percent_butters, Zmouth_butters_percent, Zoral_exploration_butters)
```





```{r PCA eigenvals and variables}
pca_composite_active_vigilance <- prcomp(composite_active_vigilance)
eig_composite_active_vigilance <- get_eig(pca_composite_active_vigilance)
vars_composite_active_vigilance <- get_pca_var(pca_composite_active_vigilance)
  
pca_composite_active_anxiety <- prcomp(composite_active_anxiety)
eig_composite_active_anxiety <- get_eig(pca_composite_active_anxiety)
vars_composite_active_anxiety <- get_pca_var(pca_composite_active_anxiety)

pca_composite_inquisitive_vigilance <- prcomp(composite_inquisitive_vigilance)
eig_composite_inquisitive_vigilance <- get_eig(pca_composite_inquisitive_vigilance)
vars_composite_inquisitive_vigilance <- get_pca_var(pca_composite_inquisitive_vigilance)

pca_composite_novel_object_interest <- prcomp(composite_novel_object_interest)
eig_composite_novel_object_interest <- get_eig(pca_composite_novel_object_interest)
vars_composite_novel_object_interest <- get_pca_var(pca_composite_novel_object_interest)
```


```{r}

corrplot(vars_composite_active_vigilance$contrib, is.corr = FALSE)
fviz_eig(pca_composite_active_vigilance, addlabels = T)
#fviz_contrib(pca_composite_active_anxiety, choice = "var", axes = 1:4)

corrplot(vars_composite_active_anxiety$contrib, is.corr = FALSE)
fviz_eig(pca_composite_active_anxiety, addlabels = T)

corrplot(vars_composite_inquisitive_vigilance$contrib, is.corr = FALSE)
fviz_eig(pca_composite_inquisitive_vigilance, addlabels = T)

corrplot(vars_composite_novel_object_interest$contrib, is.corr = FALSE)
fviz_eig(pca_composite_novel_object_interest, addlabels = T)


```


```{r structural models}

SEM_passive_vigilance_v2 <- "latentmodel_passvigi =~ Zdir_eye_contact_ffosta + Zlipsmack_ffosta + Zmovement_ffosta + Zself_gro_ffosta"
SEM_passive_vigilance_fit <- cfa(SEM_passive_vigilance_v2, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_passive_vigilance_fit, standardize = TRUE, fit.measures = TRUE)

semPaths(SEM_passive_vigilance_fit,
         layout = "tree",
         color = "gray",
         whatLabels = "std",
         edge.color = "black",
         what = "std", 
         rotation = 2,
         edge.label.cex = 1.25, 
         nCharNodes = 8, 
         sizeLat = 10, 
         sizeMan = 10, 
         title = TRUE)


SEM_active_anxiety <- 'latentmodel_activeanx =~ Zthreat_stranger_ffosta + Zself_gro_ffosta + Zstereotypy_butters + Zstation_back_ffostare + Zfreeze_back_ffosta'
SEM_active_anxiety_fit <- cfa(SEM_active_anxiety, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_active_anxiety_fit, standardize = TRUE, fit.measures = TRUE)
#SEM_active_anxiety_table <- parTable(SEM_active_anxiety_fit)



semPaths(SEM_active_anxiety_fit,
         layout = "tree",
         color = "gray",
         whatLabels = "std",
         edge.color = "black",
         what = "std", 
         rotation = 2,
         edge.label.cex = 1.25, 
         nCharNodes = 8, 
         sizeLat = 10, 
         sizeMan = 10, 
         title = TRUE)

SEM_inquisitive_vigilance <- 'latentmodel_inquivigi =~ Zcrouching_ffosta + Zstationary_front_percent_butters + ZStationary_back_butters + Zmovement_percent_butters + Ztouch_butters_percent + Zvigilant_percent_butters + Zcrouching_butters + Znonvigilant_percent_butters + Zvigi_ffosta + Zno_response_ffosta'
SEM_inquisitive_vigilance_fit <- cfa(model = SEM_inquisitive_vigilance, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_inquisitive_vigilance_fit, standardize = TRUE, fit.measures = TRUE)

semPaths(SEM_inquisitive_vigilance_fit,
         layout = "tree",
         color = "gray",
         whatLabels = "std",
         edge.color = "black",
         what = "std", 
         rotation = 2,
         edge.label.cex = 1.25, 
         nCharNodes = 8, 
         sizeLat = 10, 
         sizeMan = 10, 
         title = TRUE)


SEM_object_oriented <- 'latentmodel_objori =~ Zself_groom_percent_butters + Zmouth_butters_percent + Zoral_exploration_butters'
SEM_object_oriented_fit <- cfa(model = SEM_object_oriented, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_object_oriented_fit, standardize = TRUE, fit.measures = TRUE)

semPaths(SEM_object_oriented_fit,
         layout = "tree",
         color = "gray",
         whatLabels = "std",
         edge.color = "black",
         what = "std", 
         rotation = 2,
         edge.label.cex = 1.25, 
         nCharNodes = 8, 
         sizeLat = 10, 
         sizeMan = 10, 
         title = TRUE)

```

###################this is for class#######################
############# seminar spring 19 - questions ###############
###########################################################


```{r}
seminar_questions_sp19 <- read_excel("seminar_questions_sp19.xlsx")
str(seminar_questions_sp19)

anon_questions <- seminar_questions_sp19 %>%
  select(- person, - avatar) %>%
  filter()

seminar_questions_sp19$avatar <- as.factor(seminar_questions_sp19$avatar)

skim(anon_questions)

pca_anon_questions <- prcomp(anon_questions)
eig_anon_questions <- get_eig(pca_anon_questions)
vars_anon_questions <- get_pca_var(pca_anon_questions) 

vars_anon_questions$contrib

corrplot(vars_anon_questions$contrib, is.corr = FALSE)
fviz_eig(pca_anon_questions, addlabels = T)

transposed <- read_excel("transposed.xlsx")
View(transposed)

ggplot(transposed, aes(x=Var, y=percentage, fill=percentage)) +
  order() + 
  geom_bar(stat = "identity")

library(ggthemes)

seminar_graph <- ggplot(transposed, aes(x = reorder(Var, -percentage), y=percentage, fill = Var)) + 
  geom_bar(stat = "identity", position = "dodge") + 
 # geom_text(aes(label = percentage, y = percentage), size = 3) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip()
  
  
  
  theme_foundation() +
  theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA), #dunno
               plot.background = element_rect(colour = NA), #colors for overall border of graph
               panel.border = element_rect(colour = "black"), #colors upper corner of graph
               axis.title = element_text(face = "bold",size = rel(1)), #controls the size of the x and y axis text
               axis.title.y = element_text(angle=90,vjust =2), #vjust tells you how far the axis title will stick out from the y axis
               axis.title.x = element_text(vjust = -0.3), #vjust tells you how far the axis title will stick out from the x axis
               axis.text = element_text(angle=45), 
               axis.line = element_line(colour=NA), #y and x axis colors
               axis.ticks = element_line(), 
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(), #horizontal line descriptor 
               legend.key = element_rect(colour = NA), #legend box color
               legend.position = "bottom", #placement of the legend
               legend.direction = "horizontal", #need to figure out
               legend.key.size= unit(0.2, "cm"), #need to figure out
               legend.margin = unit(0, "cm"), #need to figure out
               legend.title = element_text(face="italic"), #need to figure out
               plot.margin=unit(c(10,5,5,5),"mm"), #need to figure out
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"), #need to figure out
               strip.text = element_text(face="bold") #need to figure out
          )

library(RColorBrewer)
seminar_graph + labs(y="Percentage", x="Questions Related To") 

```


```{r}
seminar_questions_sp19_nototals <- read_excel("seminar_questions_sp19_nototals.xlsx")
#View(seminar_questions_sp19_nototals)

anon_nototals <- seminar_questions_sp19_nototals %>%
  select(- avatar)

pca_anon_nontotals <- prcomp(anon_nototals)
eig_anon_nototals <- get_eig(pca_anon_nontotals)
vars_anon_nototals <- get_pca_var(pca_anon_nontotals) 

eigen_vals_pca_nototals <- pca_anon_nontotals$sdev^2

barplot(eigen_vals_pca_nototals)


corrplot(vars_anon_nototals$contrib, is.corr = FALSE)
fviz_eig(pca_anon_nontotals, addlabels = T)
```

===================================================================================

============================ Starting Over ========================================

===================================================================================



```{r}
##approach is changing to an efa to create a latent trait
##based on my previous pca of the data, the amount of factors that explain the majority of variance in the data range from 14-16. thus, the efa should produce 

restart_ffostare_v1 <- read_excel("znormed_ffostare_v1.xlsx")

hitnot_restart_selected_v1 <- restart_ffostare_v1 %>%
  select(- Observations, - ResultContainers, - Intervals)


#outputs between rcorr and cor are the exact same; will move forward with rcorr since it offers more
#difference between the two is that rcorr uses pairwise deletion whereas cor is a base function that pairwise manipulations have to be specified. 
rcorr_hitnot_restart_selected_v1 <- rcorr(as.matrix(hitnot_restart_selected_v1))
cor_hitnot_restart_selected_v1 <- cor(hitnot_restart_selected_v1)

smoothed_rcorr_hitnot_restart_selected_v1 <- cor.smoother(rcorr_hitnot_restart_selected_v1$r)

View(smoothed_rcorr_hitnot_restart_selected_v1$bad)

max(smoothed_rcorr_hitnot_restart_selected_v1)

parallel_hitnot_factors <- fa.parallel(smoothed_rcorr_hitnot_restart_selected_v1, n.obs = 37, fm = "minres", fa = 'fa')

##based on the output of the scree plot, the hit/not data contains 4-6 factors that explain the majority of the variation about the behaviors. 
##however, i'm using a non-positive matrix and an efa requires a positive matrix and i had to smooth it before preceding?

fa_t1_nonsmoothed <- fa(rcorr_hitnot_restart_selected_v1$r, nfactors = 4, np.obs = 37,rotate = "varimax", fm = "robust")

fa_t1_nonsmoothed$loadings %>%

fa_t2_smoothed <- fa(smoothed_rcorr_hitnot_restart_selected_v1)

print(fa_t1_nonsmoothed$loadings, cutoff=.3) 

hitnot_factanal_restart_v2 <- factanal(as.matrix(rcorr_hitnot_restart_selected_v1$r), factors = 4)
```
```{r}
#since i keep seeing the movement, direct eye contact, and lipsmack group i'm going to see how it holds up as a composite rather than a latent variable. 
library(readr)
#read in the normalized data with corrected demographic information about diet groups 
dietgroups_normalized_correct_all <- read_csv("selected_norms_composites_demgraf_v2_use.csv")
View(dietgroups_normalized_correct_all)
#filter out subjects that had a post-weaning western style diet
matdiet_only <- dietgroups_normalized_correct_all %>%
  filter(new_diet == 1) 


#set the desired variables to factors to hinge the analysis on
matdiet_only$sex <- as.factor(matdiet_only$sex)
matdiet_only$initial_diet <- as.factor(matdiet_only$initial_diet)
matdiet_only$new_diet <- as.factor(matdiet_only$new_diet)

#create composite groups based on efa/community detection output- the goal of this step was simply to investigate the subgroup outlined below
#included self groom in anx2 composite (remember also that these composites will not be in the oringinal data set above); anx1 is the same group minus self groom
matdiet_only$passive_anxiety1 <- matdiet_only$Zdir_eye_contact_ffosta + matdiet_only$Zlipsmack_ffosta + matdiet_only$Zmovement_ffosta

#check the kurtosis of the new composite(s)
skim(matdiet_only)

#test ran since it looks possible that it may suffice a distribution test
#anx1 = .0004
#anx2 = .0002
#i was wrong. variables heavily skewed.
shapiro.test(matdiet_only$passive_anxiety1)


#ran wilcox test but did not find desired pval in either case
#anx1 = .388
#anx2 = .234

matdiet_passiveanx1_wiltest_comp <- wilcox.test(matdiet_only$passive_anxiety1~matdiet_only$initial_diet)
matdiet_comp2_wiltest <- wilcox.test(matdiet_only$comp_2.2~matdiet_only$initial_diet)

matdiet_passiveanx2_wiltest_comp$p.value

#look at the data to see is the pvals make sense for each new compostie score
ggplot(matdiet_only, aes(x=initial_diet, y=passive_anxiety1, color= initial_diet)) + 
  geom_jitter(stat="identity")
```

```{r fixing the matrix}
#the steps below are for fixing the correlation matrix from our behaviors
##i'm going to make 2 matrices though. 1) will be a matrix using all behaviors from all animals (n=49), regardless of diet group and 2) will be a matrix only consisting of behaviors from mWSD offspring and controls (n=~36).
###the 'firstpass_newmatrix' below will using all animals

library(Matrix)

firstpass_newmatrix <- rcorr_hitnot_restart_selected_v1$r

PD_firstpass_newmatrix <- nearPD(firstpass_newmatrix, corr = TRUE, conv.tol = 1e-12, doSym = TRUE)

PD_firstpass_newmatrix$mat@Dimnames

norm(firstpass_newmatrix - PD_firstpass_newmatrix$mat)

#attempting to manually for using cor.smooth again
smoothcor1 <- cor.smooth(firstpass_newmatrix, eig.tol = 10^-12)


#this did not work. at all. ignore.
resid <- firstpass_newmatrix - smoothcor1

tr(resid %*% t(resid)) /2

resid

paratest1 <- fa.parallel(resid, n.obs = 37, fm = "minres")

##trying posdefify
library(sfsmisc)

posd_mat1 <- posdefify(firstpass_newmatrix, eps.ev = 1e-07)

View(posd_mat1)
View(firstpass_newmatrix)


fa.parallel(posd_mat1, n.obs = 37, fm = "minres")
```

================
new sems and pcas - 6/24/19
================

```{r setting the groups for pca}
##this chunk will be remaking the data using the new grouping with the calculated range
##these groups are based on the grouping with Damien
### going to recreate the groups like chunk above;then run it like the chunk below ->> this will give me my pca outputs for the new groups in the appropriate range
###6/19/19

group_d <- normalized_ffostare_selectvars_v1 %>%
  select(Zlipsmack_ffosta, Zmovement_ffosta, Zdir_eye_contact_ffosta, Zself_gro_ffosta)

group_e <- normalized_ffostare_selectvars_v1 %>%
  select(Zself_groom_percent_butters, Zmouth_butters_percent, Zoral_exploration_butters)

group_c <- normalized_ffostare_selectvars_v1 %>%
  select(Zstereotypy_butters, Zstation_back_ffostare, Zmanip_app_ffosta, Zthreat_stranger_ffosta, Zfreeze_back_ffosta, Znonvigi_ffosta)

group_b <- normalized_ffostare_selectvars_v1 %>%
  select(Zstationary_middle_percent_butters, Zlocomotion_percent_butters, Zhanging_behaviors_butters, Zstation_fr_ffostare, Zlocomote_ffosta, Zstereo_ffosta, Zteethgrind_ffosta, Zmouth_app_ffosta, Zeat_app_ffosta)

group_a <- normalized_ffostare_selectvars_v1 %>%
  select(ZStationary_back_butters, Zstationary_front_percent_butters, Zmovement_percent_butters, Ztactile_exploration_butters, Zvigilant_percent_butters, Zcrouching_ffosta, Zno_response_ffosta, Zvigi_ffosta)

##i'm looking at these composites within themselves ^^^
### i think they should be done within the context of the data within the whole? but how can i make sure that so i changes it to make that so... the internets say its fine to do it independently but all answers area controversial.

```

```{r running the pca for eigenvals and cariable contributions}

pca_group_e <- prcomp(group_e)
eigen_vals_group_e <- get_eig(pca_group_e)
var_pca_group_e <- get_pca_var(pca_group_e)

pca_group_d <- prcomp(group_d)
eigen_vals_group_d <- get_eig(pca_group_d)
var_pca_group_d <- get_pca_var(pca_group_d)

pca_group_c <- prcomp(group_c)
eigen_vals_group_c <- get_eig(pca_group_c)
var_pca_group_c <- get_pca_var(pca_group_c)

pca_group_b <- prcomp(group_b)
eigen_vals_group_b <- get_eig(pca_group_b)
var_pca_group_b <- get_pca_var(pca_group_b)

pca_group_a <- prcomp(group_a)
eigen_vals_group_a <- get_eig(pca_group_a)
var_pca_group_a <- get_pca_var(pca_group_a)
```

```{r visualzing the new pcas}
corrplot(var_pca_group_e$contrib, is.corr = FALSE)
fviz_eig(pca_group_e, addlabels = T)
##i chose to look at the variable contribution because it informs me about how to load the models in the next (SEM) step
##permuting the variables to create a null distribution, measure the goodness of that model and when we use other variables they give us a worse fit --> this can be done in mplus

corrplot(var_pca_group_d$contrib, is.corr = FALSE)
fviz_eig(pca_group_d, addlabels = T)

corrplot(var_pca_group_c$contrib, is.corr = FALSE)
fviz_eig(pca_group_c, addlabels = T)

corrplot(var_pca_group_b$contrib, is.corr = FALSE)
fviz_eig(pca_group_b, addlabels = T)

corrplot(var_pca_group_a$contrib, is.corr = FALSE)
fviz_eig(pca_group_a, addlabels = T)


##below is for exploring the different outputs
corrplot(var_pca_group_a$contrib, is.corr = FALSE)
fviz_eig(pca_group_e, addlabels = T)
```


```{r}
##Structural Models - 6/26/19
#the first variable (loading variable) needs to be the heaviest weighted behavior responsible for the most variability that is output in the pca output
###on that note, i may need to reorder some of theses, i did not have time to do this

cor_normalized_ffostare_selectvars_v1 <- rcorr(as.matrix(normalized_ffostare_selectvars_v1))
cormat_4_SEMS <- cor_normalized_ffostare_selectvars_v1$r

SEM_group_e <- 'latemod_group_e =~ Zself_groom_percent_butters + Zmouth_butters_percent + Zoral_exploration_butters'
SEM_group_e_fit <- cfa(model = SEM_group_e, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_group_e_fit, standardize = TRUE, fit.measures = TRUE)
  
SEM_group_d <- "latemod_group_d =~ Zdir_eye_contact_ffosta + Zlipsmack_ffosta + Zmovement_ffosta + Zself_gro_ffosta"
SEM_group_d_fit <- cfa(model = SEM_group_d, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_group_d_fit, standardize = TRUE, fit.measures = TRUE)

SEM_group_c <- "latemod_group_c =~ Zthreat_stranger_ffosta + Zself_gro_ffosta + Zstereotypy_butters + Zstation_back_ffostare + Zfreeze_back_ffosta + Zmanip_app_ffosta + Znonvigi_ffosta"
SEM_group_c_fit <- cfa(model = SEM_group_c, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_group_c_fit, standardize = TRUE, fit.measures = TRUE)


SEM_group_b <- "latemod_group_b =~ Zstationary_middle_percent_butters + Zlocomotion_percent_butters + Zhanging_behaviors_butters + Zstation_fr_ffostare + Zlocomote_ffosta + Zstereo_ffosta + Zteethgrind_ffosta + Zmouth_app_ffosta + Zeat_app_ffosta"
SEM_group_b_fit <- cfa(model = SEM_group_b, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_group_b_fit, standardize = TRUE, fit.measures = TRUE)

SEM_group_a <- "latemod_group_a =~ ZStationary_back_butters + Zstationary_front_percent_butters + Zmovement_percent_butters + Ztactile_exploration_butters + Zvigilant_percent_butters + Zcrouching_ffosta + Zno_response_ffosta + Zvigi_ffosta"
SEM_group_a_fit <- cfa(model = SEM_group_a, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_group_a_fit, standardize = TRUE, fit.measures = TRUE)

SEM_ALLMODELS_interaction <- "latemod_group_e =~ Zself_groom_percent_butters + Zmouth_butters_percent + Zoral_exploration_butters
latemod_group_d =~ Zdir_eye_contact_ffosta + Zlipsmack_ffosta + Zmovement_ffosta + Zself_gro_ffosta
latemod_group_c =~ Zthreat_stranger_ffosta + Zself_gro_ffosta + Zstereotypy_butters + Zstation_back_ffostare + Zfreeze_back_ffosta + Zmanip_app_ffosta + Znonvigi_ffosta
latemod_group_b =~ Zstationary_middle_percent_butters + Zlocomotion_percent_butters + Zhanging_behaviors_butters + Zstation_fr_ffostare + Zlocomote_ffosta + Zstereo_ffosta + Zteethgrind_ffosta + Zmouth_app_ffosta + Zeat_app_ffosta
latemod_group_a =~ ZStationary_back_butters + Zstationary_front_percent_butters + Zmovement_percent_butters + Ztactile_exploration_butters + Zvigilant_percent_butters + Zcrouching_ffosta + Zno_response_ffosta + Zvigi_ffosta"
SEM_ALLMODELS_ineraction_fit <- cfa(model = SEM_ALLMODELS_interaction, estimator = "MLR", data = normalized_ffostare_selectvars_v1)
summary(SEM_ALLMODELS_ineraction_fit, standardize = TRUE, fit.measures = TRUE)
```


#######
###############
############################
        this section will contain t-tests for new data for graphing

                6/27/19
############################
################
#######


```{r}
#removing the previous composites from the demographc information
##also removing animals that were fed a WSD postweaning
demographicinfo_34mo_hitnot <- dietgroups_normalized_correct_all %>%
  select(- comp_1, - comp_2, - comp_2.2, - comp_3, - comp_3.2, - comp_4) %>%
  filter(!new_diet == 2)
#View(demographicinfo_34mo_hitnot)

##adding the new composite groups based on correct, calculated thresholds from the community detection output
demographicinfo_34mo_hitnot$group_e <- demographicinfo_34mo_hitnot$Zlipsmack_ffosta + 
  demographicinfo_34mo_hitnot$Zmovement_ffosta + 
  demographicinfo_34mo_hitnot$Zdir_eye_contact_ffosta + 
  demographicinfo_34mo_hitnot$Zself_gro_ffosta

demographicinfo_34mo_hitnot$group_d <- demographicinfo_34mo_hitnot$Zself_groom_percent_butters + 
  demographicinfo_34mo_hitnot$Zmouth_butters_percent + 
  demographicinfo_34mo_hitnot$Zoral_exploration_butters

demographicinfo_34mo_hitnot$group_c <- demographicinfo_34mo_hitnot$Zstereotypy_butters + 
  demographicinfo_34mo_hitnot$Zstation_back_ffostare + 
  demographicinfo_34mo_hitnot$Zmanip_app_ffosta + 
  demographicinfo_34mo_hitnot$Zthreat_stranger_ffosta + 
  demographicinfo_34mo_hitnot$Zfreeze_back_ffosta + 
  demographicinfo_34mo_hitnot$Znonvigi_ffosta

demographicinfo_34mo_hitnot$group_b <- demographicinfo_34mo_hitnot$Zstationary_middle_percent_butters +
  demographicinfo_34mo_hitnot$Zlocomotion_percent_butters + 
  demographicinfo_34mo_hitnot$Zhanging_behaviors_butters + 
  demographicinfo_34mo_hitnot$Zstation_fr_ffostare + 
  demographicinfo_34mo_hitnot$Zlocomote_ffosta + 
  demographicinfo_34mo_hitnot$Zstereo_ffosta + 
  demographicinfo_34mo_hitnot$Zteethgrind_ffosta + 
  demographicinfo_34mo_hitnot$Zmouth_app_ffosta + 
  demographicinfo_34mo_hitnot$Zeat_app_ffosta

demographicinfo_34mo_hitnot$group_a <- demographicinfo_34mo_hitnot$ZStationary_back_butters +
  demographicinfo_34mo_hitnot$Zstationary_front_percent_butters +
  demographicinfo_34mo_hitnot$Zmovement_percent_butters +
  demographicinfo_34mo_hitnot$Ztactile_exploration_butters +
  demographicinfo_34mo_hitnot$Zvigilant_percent_butters + 
  demographicinfo_34mo_hitnot$Zcrouching_ffosta + 
  demographicinfo_34mo_hitnot$Zno_response_ffosta + 
  demographicinfo_34mo_hitnot$Zvigi_ffosta

#skim(demographicinfo_34mo_hitnot)

##removing extraneous behaviors to focus on the composite groups for t tests

demographicinfo_compositesonly_34mo_hitnot <- demographicinfo_34mo_hitnot %>%
  select(Observations, initial_diet, sex, group_a, group_b, group_c, group_d, group_e)


demographicinfo_compositesonly_34mo_hitnot$Observations <- as.factor(demographicinfo_compositesonly_34mo_hitnot$Observations)
demographicinfo_compositesonly_34mo_hitnot$initial_diet <-    as.factor(demographicinfo_compositesonly_34mo_hitnot$initial_diet)
demographicinfo_compositesonly_34mo_hitnot$sex <- 
  as.factor(demographicinfo_compositesonly_34mo_hitnot$sex)

skim(demographicinfo_compositesonly_34mo_hitnot)

###this chunk completes the manipulations of the data that put it in a form useful for analysis. 
###in the next chunk, i will need to do shapiro wilks for normality and run ttest on each group based on initial diet and sex. 
```








```{r}
##normality test for each composite

shapiro.test(demographicinfo_compositesonly_34mo_hitnot$group_a) ##group a is normally distributed
shapiro.test(demographicinfo_compositesonly_34mo_hitnot$group_b) ##group b is not normally distributed
shapiro.test(demographicinfo_compositesonly_34mo_hitnot$group_c) ##group c is not normally distributed
shapiro.test(demographicinfo_compositesonly_34mo_hitnot$group_d) ##group d is not normally distributed
shapiro.test(demographicinfo_compositesonly_34mo_hitnot$group_e) ##group e is not normally distributed
```


```{r}

##the top code will reflect diet results

wilco_dietresults_group_a <- t.test(demographicinfo_compositesonly_34mo_hitnot$group_a ~ demographicinfo_compositesonly_34mo_hitnot$initial_diet) 
wilco_dietresults_group_b <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_b ~ demographicinfo_compositesonly_34mo_hitnot$initial_diet)  
wilco_dietresults_group_c <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_c ~ demographicinfo_compositesonly_34mo_hitnot$initial_diet)
wilco_dietresults_group_d <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_d ~ demographicinfo_compositesonly_34mo_hitnot$initial_diet)
wilco_dietresults_group_e <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_e ~ demographicinfo_compositesonly_34mo_hitnot$initial_diet)

wilco_dietresults_group_a$p.value
##group_c remains significant 



##the bottom code will reflect sex results

wilco_sexresults_group_a <- t.test(demographicinfo_compositesonly_34mo_hitnot$group_a ~ demographicinfo_compositesonly_34mo_hitnot$sex) 
wilco_sexresults_group_b <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_b ~ demographicinfo_compositesonly_34mo_hitnot$sex)  
wilco_sexresults_group_c <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_c ~ demographicinfo_compositesonly_34mo_hitnot$sex)
wilco_sexresults_group_d <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_d ~ demographicinfo_compositesonly_34mo_hitnot$sex)
wilco_sexresults_group_e <- wilcox.test(demographicinfo_compositesonly_34mo_hitnot$group_e ~ demographicinfo_compositesonly_34mo_hitnot$sex)

wilco_sexresults_group_d$p.value
##group_d is now significant



##this chunk of determining diet and sex differences is complete
##i am not considering adding back the new_diet == 2 subjects because the question revolves around maternal diet and anxiety expression
##next, in order to graph these, i will need to put each in a their own dataset so i can graph the composite scores for each diet group. i will need to add error bars in the form. that code is somewhere ((maybe methods_doc?)) 
```


```{r}
##isolating the means for graphing
##need to also add error bars in the form of standard errors
##meanval_group_a_1 = meanvalue of the normal diet individuals


##############################group_a

group_a1_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 1) %>%
  select(group_a)
#View(group_a1_vals)
mean_group_a1_vals <- mean(group_a1_vals$group_a)
stder_group_a1_vals <- sd(group_a1_vals$group_a)/sqrt(length(group_a1_vals$group_a))
#mean_group_a1_vals
group_a2_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 2) %>%
  select(group_a)
#View(group_a1_vals)
mean_group_a2_vals <- mean(group_a2_vals$group_a)
stder_group_a2_vals <- sd(group_a2_vals$group_a)/sqrt(length(group_a2_vals$group_a))
#stder_group_a2_vals
mean_group_a2_vals

###############################end group_a

##############################start group_b

group_b1_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 1) %>%
  select(group_b)
#View(group_a1_vals)
mean_group_b1_vals <- mean(group_b1_vals$group_b)
stder_group_b1_vals <- sd(group_b1_vals$group_b)/sqrt(length(group_b1_vals$group_b))
#mean_group_a1_vals
group_b2_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 2) %>%
  select(group_b)
#View(group_a1_vals)
mean_group_b2_vals <- mean(group_b2_vals$group_b)
stder_group_b2_vals <- sd(group_b2_vals$group_b)/sqrt(length(group_b2_vals$group_b))
#mean_group_a2_vals

###############################end group_b

##############################start group_c

group_c1_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 1) %>%
  select(group_c)
#View(group_a1_vals)
mean_group_c1_vals <- mean(group_c1_vals$group_c)
stder_group_c1_vals <- sd(group_c1_vals$group_c)/sqrt(length(group_c1_vals$group_c))
#mean_group_a1_vals
group_c2_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 2) %>%
  select(group_c)
#View(group_a1_vals)
mean_group_c2_vals <- mean(group_c2_vals$group_c)
stder_group_c2_vals <- sd(group_c2_vals$group_c)/sqrt(length(group_c2_vals$group_c))
#mean_group_a2_vals

###############################end group_c

##############################start group_d

group_d1_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 1) %>%
  select(group_d)
#View(group_a1_vals)
mean_group_d1_vals <- mean(group_d1_vals$group_d)
stder_group_d1_vals <- sd(group_d1_vals$group_d)/sqrt(length(group_d1_vals$group_d))
#mean_group_a1_vals
group_d2_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 2) %>%
  select(group_d)
#View(group_a1_vals)
mean_group_d2_vals <- mean(group_d2_vals$group_d)
stder_group_d2_vals <- sd(group_d2_vals$group_d)/sqrt(length(group_d2_vals$group_d))
#mean_group_a2_vals

###############################end group_d

##############################start group_e

group_e1_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 1) %>%
  select(group_e)
#View(group_a1_vals)
mean_group_e1_vals <- mean(group_e1_vals$group_e)
stder_group_e1_vals <- sd(group_e1_vals$group_e)/sqrt(length(group_e1_vals$group_e))
#mean_group_a1_vals
group_e2_vals <- demographicinfo_compositesonly_34mo_hitnot %>%
  filter(initial_diet == 2) %>%
  select(group_e)
#View(group_a1_vals)
mean_group_e2_vals <- mean(group_e2_vals$group_e)
stder_group_e2_vals <- sd(group_e2_vals$group_e)/sqrt(length(group_e2_vals$group_e))
sd_e2 <- sd(group_e2_vals$group_e)

se_e2 <- sd_e2/sqrt(length(group_e2_vals$group_e))

se_e2
stder_group_e2_vals
#mean_group_a2_vals

###############################end group_e

###end chunk
### here, we created a mean value and a st.err value that will be used to visualize the data after combining it into a single table

```


```{r}
##make a table
dietgroup_avg_vals <- c(mean_group_a1_vals, mean_group_b1_vals, mean_group_c1_vals, mean_group_d1_vals, mean_group_e1_vals, mean_group_a2_vals, mean_group_b2_vals, mean_group_c2_vals, mean_group_d2_vals, mean_group_e2_vals) 
dietgroup_stderr_vals <- c(stder_group_a1_vals, stder_group_b1_vals, stder_group_c1_vals, stder_group_d1_vals, stder_group_e1_vals, stder_group_a2_vals,  stder_group_b2_vals, stder_group_c2_vals, stder_group_d2_vals, stder_group_e2_vals)
dietgroup_vector_vals <- c(1,1,1,1,1,2,2,2,2,2)
dietgroup_vector_titles <- c("Group A",
                             "Group B",
                             "Group C*",
                             "Group D",
                             "Group E",
                             "Group A",
                             "Group B",
                             "Group C*",
                             "Group D",
                             "Group E")
dietgroup_meanvals_table1 <- data.frame(dietgroup_vector_titles, dietgroup_vector_vals, dietgroup_avg_vals, dietgroup_stderr_vals)

dietgroup_meanvals_table1$dietgroup_vector_titles <- as.factor(dietgroup_meanvals_table1$dietgroup_vector_titles)
dietgroup_meanvals_table1$dietgroup_vector_vals <- as.factor(dietgroup_meanvals_table1$dietgroup_vector_vals)
#dietgroup_meanvals_table1$dietgroup_stderr_vals <- as.numeric(dietgroup_meanvals_table1$dietgroup_stderr_vals)

View(dietgroup_meanvals_table1)

ggplot(dietgroup_meanvals_table1, aes(x=dietgroup_vector_titles, y= dietgroup_avg_vals, fill=dietgroup_vector_vals)) + geom_boxplot(stat="identity", position = position_dodge())

library(ggthemes)

dietdifferences_plot <- ggplot(dietgroup_meanvals_table1, aes(x=dietgroup_vector_titles, y=dietgroup_avg_vals, fill = dietgroup_vector_vals)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  geom_errorbar(aes(ymin=(dietgroup_avg_vals)-dietgroup_stderr_vals,
                    ymax=(dietgroup_avg_vals)+dietgroup_stderr_vals),
                    width = .2,
                    position = position_dodge(.9),
                    size = .8) +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values= wes_palette(n=2, "Darjeeling1")) +
  theme_foundation() +
  theme(plot.title = element_text(face = "bold",
               size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA), #dunno
               plot.background = element_rect(colour = NA), #colors for overall border of graph
               panel.border = element_rect(colour = "black"), #colors upper corner of graph
               axis.title = element_text(face = "bold",size = rel(1)), #controls the size of the x and y axis text
               axis.title.y = element_text(angle=90,vjust =2), #vjust tells you how far the axis title will stick out from the y axis
               axis.title.x = element_text(vjust = -0.3), #vjust tells you how far the axis title will stick out from the x axis
               axis.text = element_text(), 
               axis.line = element_line(colour=NA), #y and x axis colors
               axis.ticks = element_line(), 
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(), #horizontal line descriptor 
               legend.key = element_rect(colour = NA), #legend box color
               legend.position = "bottom", #placement of the legend
               legend.direction = "horizontal", #need to figure out
               legend.key.size= unit(0.2, "cm"), #need to figure out
               legend.margin = unit(0, "cm"), #need to figure out
               legend.title = element_text(face="italic"), #need to figure out
               plot.margin=unit(c(10,5,5,5),"mm"), #need to figure out
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"), #need to figure out
               strip.text = element_text(face="bold") #need to figure out
          )


diet_diff_final <- dietdifferences_plot + labs(x = 'Composite Group', y = 'Composite Score', title = "Diet Group Differences", caption = "Control = Green / WSD = Orange / *p=.029") + guides(fill=guide_legend(title = ""))

png('diet_diff_final.png')
print(diet_diff_final)
dev.off()

ggsave('diet_diff_final.png')
```
